name: "Build and push docker image to dockerhub"

on:
  push:
    branches:
      ["main"]
  pull_request:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        
      - name: Login to dockehub
        uses: docker/login-action@v3
        with: 
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_PASSWORD}}

      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with: 
          context: .
          push: ${{ github.event_name == 'push' }}
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/test_app:latest
    
